version: '3'
services:
  dehydrated-duckdns:
    image: duckdns-dehydrated
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dehydrated-duckdns
    restart: unless-stopped
    network_mode: host
    volumes:
      - ./data:/data
    environment:
      - DUCKDNS_TOKEN=token
      - CRON_SCHEDULE=0 0 */7 * * # (default)
      - MAIN_DOMAIN=yourdomain.duckdns.org
      - SUBDOMAINS=*.yourdomain.duckdns.org
      - DEHYDRATED_CONTACT_EMAIL=yourmail@mail.com
      - DEHYDRATED_CA=letsencrypt-test #(default: letsencrypt)
      - FORCE_RUN=true # (default: false)
